description: >
  Allows the stock kubectl client to work with Amazon EKS.
  Installs the AWS IAM Authenticator for Kubernetes and
  updates the kubectl configuration file to use the AWS IAM Authenticator.

parameters:
  cluster-name:
    description: |
      The name of the cluster for which to create a kubeconfig entry.
    type: string
  aws-region:
    description: |
      The AWS region that the cluster is in. If not specified, the configured default
      region for your AWS CLI installation will be used.
    type: string
    default: ""
  kubeconfig-file-path:
    description: |
      Specifies a kubeconfig file to append the configuration details to.
      By default, the configuration is written to the first file path in the
      KUBECONFIG environment variable (if it is set) or the default kubeconfig
      path (.kube/config) in your home directory.
    type: string
    default: ""
  cluster-authentication-role-arn:
    description: |
      To assume a role for cluster authentication, specify an IAM role ARN with
      this option. For example, if you created a cluster while assuming an IAM
      role, then you must also assume that role to connect to the cluster the
      first time.
    type: string
    default: ""
  cluster-context-alias:
    description: |
      Alias for the cluster context name. If a value is not specified,
      the cluster context name will be set to match the cluster ARN.
    type: string
    default: ""
  dry-run:
    description: |
      Print the merged kubeconfig to stdout instead of writing it to file.
    type: boolean
    default: false
  verbose:
    description: |
      Print more detailed output when writing to the kubeconfig file.
    type: boolean
    default: false
  platform:
    description: |
      The platform on which to install the AWS IAM Authenticator.
      This parameter is ignored when skip-authenticator-install is set to true.
    type: enum
    default: "linux"
    enum: ["linux", "darwin"]
  skip-authenticator-install:
    description: |
      Whether to skip the installation of the AWS IAM Authenticator.
    type: boolean
    default: false

steps:
  - unless:
      condition: << parameters.skip-authenticator-install >>
      steps:
        - install-aws-iam-authenticator:
            platform: << parameters.platform >>
  - aws-cli/install
  - run:
      name: Update the kubectl configuration file to use the authenticator
      command: |
        CLUSTER_NAME="<< parameters.cluster-name >>"
        AWS_REGION="<< parameters.aws-region >>"
        KUBECONFIG_FILE_PATH="<< parameters.kubeconfig-file-path >>"
        ROLE_ARN="<< parameters.cluster-authentication-role-arn >>"
        CLUSTER_CONTEXT_ALIAS="<< parameters.cluster-context-alias >>"
        DRY_RUN="<< parameters.dry-run >>"
        VERBOSE="<< parameters.verbose >>"
        if [ -n "${CLUSTER_NAME}" ]; then
            set -- "$@" --name "${CLUSTER_NAME}"
        fi
        if [ -n "${AWS_REGION}" ]; then
            set -- "$@" --region "${AWS_REGION}"
        fi
        if [ -n "${KUBECONFIG_FILE_PATH}" ]; then
            set -- "$@" --kubeconfig "${KUBECONFIG_FILE_PATH}"
        fi
        if [ -n "${ROLE_ARN}" ]; then
            set -- "$@" --role-arn "${ROLE_ARN}"
        fi
        if [ -n "${CLUSTER_CONTEXT_ALIAS}" ]; then
            set -- "$@" --alias "${CLUSTER_CONTEXT_ALIAS}"
        fi
        if [ "${DRY_RUN}" == "true" ]; then
            set -- "$@" --dry-run
        fi
        if [ "${VERBOSE}" == "true" ]; then
            set -- "$@" --verbose
        fi
        aws eks update-kubeconfig "$@"
